"""empty message

Revision ID: b7787946dbc1
Revises: c49c37c7446c
Create Date: 2023-07-22 01:26:57.494561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7787946dbc1'
down_revision = 'c49c37c7446c'
branch_labels = None
depends_on = None

def get_foreign_key_constraint_name(table_name, column_name, ref_table_name):
    insp = sa.inspect(op.get_bind())
    constraints = insp.get_foreign_keys(table_name)
    for constraint in constraints:
        if constraint['referred_table'] == ref_table_name and column_name in constraint['constrained_columns']:
            return constraint['name']
    return None

def remove_foreign_key_constraint(table_name, column_name, ref_table_name):
    constraint_name = get_foreign_key_constraint_name(table_name, column_name, ref_table_name)
    if constraint_name:
        with op.batch_alter_table(table_name, schema=None) as batch_op:
            batch_op.drop_constraint(constraint_name, type_='foreignkey')

def upgrade():
    # Resto do código de upgrade...

    with op.batch_alter_table('adoption_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        remove_foreign_key_constraint('adoption_process', 'adopter_id', 'user')
        batch_op.create_foreign_key('fk_user_id', 'user', ['user_id'], ['id'])
        batch_op.drop_column('adopter_id')

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adoption_process', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adopter_id', sa.INTEGER(), nullable=False))
        # Consultar o nome real da foreign key
        constraint_name = get_foreign_key_constraint_name('adoption_process', 'user_id', 'user')
        batch_op.drop_constraint(constraint_name, type_='foreignkey')
        batch_op.create_foreign_key('fk_adopter_id', 'user', ['adopter_id'], ['id'])
        batch_op.drop_column('user_id')


    # ### end Alembic commands ###
