"""tabela de adocao

Revision ID: c49c37c7446c
Revises: f0f5fefb2d2e
Create Date: 2023-07-22 01:07:31.510096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c49c37c7446c'
down_revision = 'f0f5fefb2d2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adoption_process',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('adopter_id', sa.Integer(), nullable=False),
    sa.Column('kit_cuidados', sa.Boolean(), nullable=True),
    sa.Column('visita_marcada', sa.Date(), nullable=True),
    sa.Column('entrevista_marcada', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['adopter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adoption_process')
    # ### end Alembic commands ###
